/*
@TargetNode='192.0.0.1'
@GeneratedBy=admin
@GenerationDate=11/21/2022 19:40:29
@GenerationHost=TestServer
*/

instance of MSFT_UserRightsAssignment as $MSFT_UserRightsAssignment5ref
{
ResourceID = "[UserRightsAssignment][V-26473][medium][Allow log on through Remote Desktop Services]::[WindowsServer]WindowsServerADStig";
 Force = True;
 Policy = "Allow_log_on_through_Remote_Desktop_Services";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\PowerSTIG\\4.3.0\\DSCResources\\Resources\\windows.UserRightsAssignment.ps1::56::5::UserRightsAssignment";
 Identity = {
    "Builtin\\Administrators"
};
 ModuleName = "SecurityPolicyDsc";
 ModuleVersion = "2.4.0.0";

 ConfigurationName = "PowerStigConfiguration";

};
instance of MSFT_RegistryPolicyFile as $MSFT_RegistryPolicyFile2ref
{
ResourceID = "[RegistryPolicyFile][V-46475][medium][DTBI015-IE11-Warning of certificate mismatch]::[InternetExplorer]BrowserStig";
 ValueName = "WarnOnBadCertRecving";
 Ensure = "Present";
 Key = "Software\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings";
 ValueData = {
    "1"
};
 SourceInfo = "C:\\ContentStore\\DSC\\Modules\\PowerSTIG\\4.3.0\\DSCResources\\Resources\\windows.Registry.ps1::40::13::RegistryPolicyFile";
 ValueType = "Dword";
 ModuleName = "GPRegistryPolicyDsc";
 TargetType = "ComputerConfiguration";
 ModuleVersion = "1.2.0";

 ConfigurationName = "PowerStigConfiguration";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0"; 
 ContentType="PasswordEncrypted";
 

                        MinimumCompatibleVersion = "1.0.0";
 

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 

                        Author="xadmin";
 

                        GenerationDate="03/09/2021 19:40:29";
 

                        GenerationHost="TestServer";
 

                        Name="PowerStigConfiguration";


                    };