name: Pester
on:
  push:
    branches: [ main ]
jobs:
  unit-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Pester tests
      run: |
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module -Name Pester -RequiredVersion 5.0.4 -Confirm:$false -Force
        Install-Module -Name PSDesiredStateConfiguration -RequiredVersion 2.0.5 -Confirm:$false -AllowClobber -Force
        $result = Invoke-Pester -Path *.Tests.ps1 -PassThru -Show All
        if ($result.FailedCount -gt 0)
        {
          exit 1
        }
        else
        {
          exit 0
        }
      shell: pwsh
  
  git-version:
    runs-on: windows-latest
    steps:
      - name: Install-GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
         versionSpec: '5.x'
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Show GitVersion
        run: |
          Write-Output ${{ steps.gitversion.outputs }}
