name: Pester
on:
  push:
    branches: [ main ]
jobs:
  unit-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module -Name Pester -RequiredVersion 5.0.4 -Confirm:$false -Force
        Install-Module -Name PSDesiredStateConfiguration -RequiredVersion 2.0.5 -Confirm:$false -AllowClobber -Force   
      shell: pwsh
    - name: Run Pester
      id: run_pester
      uses: zyborg/pester-tests-report@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_name: module_tests
        report_title: PortableLcm Tests
    - name: Export test results
      shell: pwsh
      run: |
        Write-Host 'Total Tests Executed...:  ${{ steps.run_pester.outputs.total_count }}'
        Write-Host 'Total Tests PASSED.....:  ${{ steps.run_pester.outputs.passed_count }}'
        Write-Host 'Total Tests FAILED.....:  ${{ steps.run_pester.outputs.failed_count }}'
